name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: sudo ./install.sh

      - name: Install Rust stable
        run: |
          rustup toolchain update --no-self-update stable
          rustup default stable

      - name: Create dummy certificates
        run: |
          touch certificates/root.pem
          touch certificates/client.crt
          touch certificates/ascii-pay-client.pem

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
